orb validate

diff --git a/src/commands/publish-helm.yml b/src/commands/publish-helm.yml
--- a/src/commands/publish-helm.yml
+++ b/src/commands/publish-helm.yml
@@ -3,44 +3,44 @@ description: >
 
 steps:
 - run:
-  name: Publish
-  command: |
-    ## Get chart version and make sure it's an updated version
+    name: Publish
+    command: |
+        ## Get chart version and make sure it's an updated version
 
-    CHART_VERSION=$(yq r Chart.yaml version)
+        CHART_VERSION=$(yq r Chart.yaml version)
 
-    if [ "$CHART_VERSION" == "null" ]; then
-        echo "Could not find chart version"
-        exit 1
-    fi
+        if [ "$CHART_VERSION" == "null" ]; then
+            echo "Could not find chart version"
+            exit 1
+        fi
 
-    set +e # allow grep to fail
-    git --no-pager tag | grep $CHART_VERSION
+        set +e # allow grep to fail
+        git --no-pager tag | grep $CHART_VERSION
 
-    if [ $? == 0 ]; then
-        echo "Chart with version ${CHART_VERSION} has already been published"
-        exit 0
-    fi
+        if [ $? == 0 ]; then
+            echo "Chart with version ${CHART_VERSION} has already been published"
+            exit 0
+        fi
 
-    set +e
+        set +e
 
-    git tag $CHART_VERSION
-    git push origin $CHART_VERSION
+        git tag $CHART_VERSION
+        git push origin $CHART_VERSION
 
-    ## Package with helm and upload to the helm-charts releases
+        ## Package with helm and upload to the helm-charts releases
 
-    helm package . --destination .deploy
-    cr upload -o pennlabs -r helm-charts -p .deploy
+        helm package . --destination .deploy
+        cr upload -o pennlabs -r helm-charts -p .deploy
 
-    ## Publish to helm-charts by cloning down with personal access token
+        ## Publish to helm-charts by cloning down with personal access token
 
-    cd ..
-    git clone https://github.com/pennlabs/helm-charts
-    cd helm-charts
-    git remote rm origin
-    git remote add origin "https://pennappslabs:${CR_TOKEN}@github.com/pennlabs/helm-charts.git"
-    git checkout gh-pages
-    cr index -i index.yaml -p .deploy -o pennlabs -r helm-charts --charts-repo https://github.com/pennlabs/helm-charts
-    git add index.yaml
-    git commit -m "release new version [ci skip]"
-    git push
+        cd ..
+        git clone https://github.com/pennlabs/helm-charts
+        cd helm-charts
+        git remote rm origin
+        git remote add origin "https://pennappslabs:${CR_TOKEN}@github.com/pennlabs/helm-charts.git"
+        git checkout gh-pages
+        cr index -i index.yaml -p .deploy -o pennlabs -r helm-charts --charts-repo https://github.com/pennlabs/helm-charts
+        git add index.yaml
+        git commit -m "release new version [ci skip]"
+        git push
